### ISSUE TITLE
Agent geometry?

### ISSUE THREAD

**Issue by JD-ETH** [MIT-TESSE/tesse-core#1]
I am looking for ways to understand the collisions better in the simulation. where can I find the geometrical definition of the agent? For now it seems like it's floating at ~0,5 meters above ground but I can't seem to find the exact geometry of it.

**Comment by griffith826** [comment]
Hi, sorry for the delay. The agent's capsule collider has a radius of 0.125 and height of 0.5. It's defined in https://github.com/MIT-TESSE/tesse-core/blob/master/prefabs/tesse_multiscene_agent.prefab#L507, which I can imagine is nearly impossible to find without using the Unity Editor.

**Comment by JD-ETH** [comment]
Haha yeah no kidding. I'm not familiar with Unity :) Thanks!
